services:
  postgres:
    image: postgres:15
    container_name: quiz_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vocabulary_quiz 
      POSTGRES_PASSWORD: vocabulary_quiz
      POSTGRES_DB: vocabulary_quiz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: quiz_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
